#include <stdio.h>
#include <limits.h>

int NumAnimals, quietest;
int noise[11][11];

// declare the functions for computing the permutation and generated noise of each possible arrangement
void permute(int * animals, int level, int * curArrange, int * used);
int sumNoise(const int * curArrange);


//Permutation with recursion
void permute(int * animals, int level, int * curArrange, int * used){
    for (int i=0; i<NumAnimals; i++){
        // check if the value was already used
        if (used[i]) {
            continue;
        }
        //making value used
        used[i]=1;
        curArrange[level] = animals[i]; // assigning the animal to the current level

        // check if the current arrangement is completed
        if (level == NumAnimals-1){
            //call the function that computes the generated noise for the current arrangement
            int total = sumNoise(curArrange);
            //compare the generated noise of current arrangement  with generated noise of previous arrangement
            if(quietest >= total){
                quietest = total;
            }
        } else {    //if not all animals were used
            //do the recursion
            permute(animals, level + 1, curArrange, used);
        }
        used[i]=0;  //unmake value used
    }
}


//Function for computing the sum of noise
int sumNoise(const int * curArrange){
    int sum=0, left, right;

    for (int n=0; n<NumAnimals; n++) {

        //Compute antagonization from animals on the left
        if (n>1) {
            left = noise[curArrange[n]][curArrange[n-1]] + noise[curArrange[n]][curArrange[n-2]];  //base case
        }
        if (n==1){
            left = noise[curArrange[n]][curArrange[n-1]];   //only one animal on the left
        }
        if (n==0){
            left=0; //no animals on the left
        }

        //Compute antagonization from animals on the right
        if (n<NumAnimals-2) {
            right = noise[curArrange[n]][curArrange[n+1]] + noise[curArrange[n]][curArrange[n+2]];  //base case
        }
        if (n== NumAnimals-2){
            right = noise[curArrange[n]][curArrange[n+1]];  //only one animal on the right
        }
        if (n==NumAnimals-1){
            right=0;    //no animals on the right
        }

        sum += left + right;    //calculate the noise of the individual animal and add to the overall noise from all animals
        left = 0;   //clear antagonization from left
        right = 0;  //clear antagonization from right
    }
    return sum;
}


int main() {
    scanf("%d", &NumAnimals); //the number of animal in exhibition

    // 2D array for noise relation between animals
    //scan the values of noise level generated by animal j when antagonized by animal i
    for (int j=0; j<NumAnimals; j++){
        for (int i=0; i<NumAnimals; i++){
            scanf("%d", &(noise[j][i]));
        }
    }

    int animals[NumAnimals], curArrange[NumAnimals], used[NumAnimals];

    // Assign individual number for each animal
    for (int a=0; a<NumAnimals; a++) {
        animals[a] = a;
    }
    //Emptying all arrays to start
    for (int n=0; n<NumAnimals; n++){
        curArrange[n]=0;
        used[n]=0;
    }
    // assigning the largest possible int number to the quietest
    // to compare it with generated noise of each animal combination
    // to fiend the smallest generated noise
    quietest = INT_MAX;

    //call the recursive functions
    permute(animals, 0, curArrange, used);
    printf("%d", quietest);
    return 0;
}



